insert into issue_clusters (slug, title, category, description, fix_status, confidence, is_public) values
  ('performance_regression', 'FPS / performance regression since 1.13.00', 'performance',
   'Frame-rate drops, stutter, and frame-pacing issues reported after patch 1.13.00 across PC and console.',
   'reported', 'seed_unverified', true),
  ('crash_startup_hang', 'Crashes and startup hangs', 'crash_startup',
   'Crashes to desktop/home and hangs at or shortly after launch.',
   'reported', 'seed_unverified', true),
  ('map_open_crash_persistent', 'Map-open crash (persists after claimed fix)', 'crash_startup',
   'Patch notes claimed a fix for crashes when opening the map; reports indicate it still occurs.',
   'persists', 'seed_unverified', true),
  ('boss_rematch_crash_persistent', 'Boss rematch crash (persists after claimed fix)', 'crash_startup',
   'Patch notes claimed a fix for crashes when rematching bosses; reports indicate it still occurs.',
   'persists', 'seed_unverified', true),
  ('controls_input_gameplay', 'Mount, input, and title-screen lockups', 'controls_gameplay',
   'Horse/mount control failures, unresponsive inputs, and title-screen lockups.',
   'reported', 'seed_unverified', true),
  ('hardware_driver_specific', 'Hardware/driver-specific issues', 'performance',
   'Reports tied to specific hardware or drivers: AMD 26.6.2+, GTX 1060 with FSR/frame-gen, NVIDIA laptop and high-end GPUs.',
   'reported', 'seed_unverified', true),
  ('combat_airborne_cancel', 'Airborne maneuvers canceling mid-combat', 'controls_gameplay',
   'Low-confidence reports of airborne combat maneuvers canceling. Hidden from public top issues until direct submissions confirm.',
   'reported', 'seed_unverified', false);
